### ISSUE TITLE
Investigation on (Skype: ) helene.rblx

### ISSUE THREAD

**Issue by EXYZED** [ASIS-AUS/InvestigationsBureau#1]
# Main Background information
***
* Threatened to DDOS UK_SBS
* Leaked **ROBLOX** technology.

**Comment by EXYZED** [comment]
https://www.roblox.com/users/45308528/profile

**Comment by M3ASURE** [comment]
The user **Helene_IS** has stolen technology from **TurkishAviator**, after asking a friend to do it for her. **(http://prntscr.com/fimx0k)**

User has threatened to DDoS **'UK_SBS'** **(http://prntscr.com/fimxb5)**

**Comment by EXYZED** [comment]
https://plus.google.com/101400861623336565916
- May be a shared account.

**Comment by EXYZED** [comment]
https://www.youtube.com/watch?v=arbGTdxHpZg
* Potentially her youtube channel

**Comment by CrozzRoadz** [comment]
Possible old Twitter account
ShayeHuiRBLX

**Comment by EXYZED** [comment]
Twitter is an android.
![screen shot 2017-06-11 at 23 17 44](https://user-images.githubusercontent.com/18582414/27015023-3b0a2660-4efc-11e7-9d43-cc283088481a.png)

**Comment by EXYZED** [comment]
> **A quote from her status on ROBLOX** "Theresa May is not my prime minister!1!"
She may reside in the United Kingdom.

![screen shot 2017-06-11 at 23 21 03](https://user-images.githubusercontent.com/18582414/27015039-beb33344-4efc-11e7-9f73-b98eac0174e8.png)

**Comment by EXYZED** [comment]
![screen shot 2017-06-11 at 23 23 12](https://user-images.githubusercontent.com/18582414/27015045-f608f9c8-4efc-11e7-9354-8455e98a42b2.png)

Past usernames might help?

**Comment by CrozzRoadz** [comment]
**Steam Profile**
http://steamcommunity.com/profiles/76561198267660950

**Comment by EXYZED** [comment]
https://www.twitch.tv/forcestoworld

**Comment by EXYZED** [comment]
https://plus.google.com/102268885530924734528

**Comment by EXYZED** [comment]
https://www.flickr.com/photos/136634139@N07/albums/
Flickr identified by @CrozzRoadz

**Comment by CrozzRoadz** [comment]
**Discord**
Hélène#8597
