### ISSUE TITLE
Australian National Defence - 

### ISSUE THREAD

**Issue by EXYZED** [ASIS-AUS/InvestigationsBureau#3]
Threat Levels at **EXPECTED**

Melodramatic rivalry against another [AUSTRALIA](https://www.roblox.com/Groups/group.aspx?gid=3274414),

**Comment by EXYZED** [comment]
http://prntscr.com/fkn2q5
http://prntscr.com/fkn31m
http://prntscr.com/fkn3go

**Comment by EXYZED** [comment]
https://trello.com/c/5RsEGhxz/105-aus-australia

Blacklisted from RNC due to **rival**ry comments.

**Comment by EXYZED** [comment]
- Their ADF Discord : SYnFeK3

**Comment by AdamMorality** [comment]
Should we have random discord accounts in their adf discord?
